-- Intentionally empty.
-- Production-derived records, phone numbers, emails, and password hashes must never be committed.
-- Add synthetic development fixtures through reviewed, deterministic seed scripts only.
