// Shared day code mapping for session scheduling
export const DAY_CODE_MAP: Record<string, { code: 'SU' | 'MO' | 'TU' | 'WE' | 'TH' | 'FR' | 'SA'; index: number }> = {
    SU: { code: 'SU', index: 0 },
    SUN: { code: 'SU', index: 0 },
    SUNDAY: { code: 'SU', index: 0 },
    MO: { code: 'MO', index: 1 },
    MON: { code: 'MO', index: 1 },
    MONDAY: { code: 'MO', index: 1 },
    TU: { code: 'TU', index: 2 },
    TUE: { code: 'TU', index: 2 },
    TUESDAY: { code: 'TU', index: 2 },
    WE: { code: 'WE', index: 3 },
    WED: { code: 'WE', index: 3 },
    WEDNESDAY: { code: 'WE', index: 3 },
    TH: { code: 'TH', index: 4 },
    THU: { code: 'TH', index: 4 },
    THURSDAY: { code: 'TH', index: 4 },
    FR: { code: 'FR', index: 5 },
    FRI: { code: 'FR', index: 5 },
    FRIDAY: { code: 'FR', index: 5 },
    SA: { code: 'SA', index: 6 },
    SAT: { code: 'SA', index: 6 },
    SATURDAY: { code: 'SA', index: 6 },
};
