import { describe, expect, it } from 'vitest';

import { getAiReportGenerationSkipReason } from '@/lib/services/aiReportGuards';

describe('getAiReportGenerationSkipReason', () => {
  it('allows generation when no report exists yet', () => {
    expect(getAiReportGenerationSkipReason(null)).toBeNull();
  });

  it('skips reports that were already generated by AI', () => {
    expect(getAiReportGenerationSkipReason({ status: 'DRAFT', is_ai_generated: true })).toContain('already generated');
  });

  it('skips existing manual reports too', () => {
    expect(getAiReportGenerationSkipReason({ status: 'SUBMITTED', is_ai_generated: false })).toContain('already exists');
  });

  it('skips existing reports even when the AI flag is null', () => {
    expect(getAiReportGenerationSkipReason({ status: 'DRAFT', is_ai_generated: null })).toContain('already exists');
  });

  it('includes the current status in the skip reason', () => {
    expect(getAiReportGenerationSkipReason({ status: 'PUBLISHED', is_ai_generated: true })).toContain('PUBLISHED');
  });
});
